
GET http://localhost:3333/courses


###
POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de docker"
}


###
GET http://localhost:3333/courses/00b05611-ac6a-42b7-8d26-d1b8e6a19b5c