
GET http://localhost:3333/courses

###
GET http://localhost:3333/courses/6066098f-bcce-4fc4-ae02-8cf97901b81b


###
POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de NodeJs"
}